DROP TABLE IF EXISTS users,mpa,genres,film_genres,film_likes,films,friends;
CREATE TABLE IF NOT EXISTS users (
                       id INTEGER GENERATED BY DEFAULT  AS IDENTITY PRIMARY KEY,
                       login VARCHAR(32) NOT NULL,
                       name VARCHAR(32) NOT NULL,
                       email VARCHAR(128) NOT NULL,
                       birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS friends (
                         user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
                         friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
                         status INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mpa (
                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(128) NOT NULL,
                       release_date DATE NOT NULL,
                       description VARCHAR(256) NOT NULL,
                       duration INTEGER NOT NULL,
                       rate INTEGER ,
                       mpa_id INTEGER REFERENCES mpa (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS genres (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_likes (
                            film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
                            user_id INTEGER REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_genres (
                             film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
                             genre_id INTEGER REFERENCES genres (id) ON DELETE CASCADE
);



